server:
  port: 9012
  
my:
  prop:
    one: ${propOne:defaultProp1}
    two: ${propTwo:defaultProp2}
    three:

management:
  security:
    enabled: false

endpoints:
  env:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true
  info:
    enabled: true


    